#!/usr/bin/sh
# Written by treewolf
# Must be run with root permissions

iptables -F
iptables -X

# Setup default policies
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT DROP
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT

# Enable loopback access
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

# Enable pinging
iptables -A INPUT -i all -p icmp --icmp-type echo-reply -j ACCEPT
iptables -A OUTPUT -o all -p icmp --icmp-type echo-request -j ACCEPT

# List ports incoming
iptables -A INPUT -i all -p udp --sport 53 --dport 53 -j ACCEPT
iptables -A INPUT -i all -p udp -m multiport --sport 68,67 -m multiport --dport 67,68 -j ACCEPT
iptables -A INPUT -i all -p udp --sport 123 --dport 123 -j ACCEPT
iptables -A INPUT -i all -p udp --sport 636 --dport 636 -j ACCEPT

iptables -A INPUT -i all -p tcp --sport 22 --dport 22 -m --state ESTABLISHED,RELATED -j ACCEPT
iptables -A INPUT -i all -p tcp -m multiport --sport 80,443 -m multiport --dport 80,443 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -i all -p tcp --sport 631 --dport 631 -j ACCEPT
iptables -A INPUT -i all -p tcp --sport 636 --dport 636 -j ACCEPT

# List ports outgoing
iptables -A OUTPUT -o all -p udp --sport 53 --dport 53 -j ACCEPT
iptables -A OUTPUT -o all -p udp --sport 123 --dport 123 -j ACCEPT
iptables -A OUTPUT -o all -p udp --sport 636 --dport 636 -j ACCEPT

iptables -A OUTPUT -o all -p tcp --sport 22 --dport 22 -j ACCEPT
iptables -A OUTPUT -o all -p tcp -m multiport --sport 80,443 -m multiport --dport 80,443 -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -o all -p tcp --sport 631 --dport 631 -j ACCEPT
iptables -A OUTPUT -o all -p tcp --sport 636 --dport 636 -j ACCEPT

iptables-save > /etc/iptables/iptables.rules
systemctl enable iptables.service
systemctl start iptables.service
